quiz/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "quiz"

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('teacher/', views.TeacherRegister, name='TeacherRegister'),
    path('student/', views.StudentRegister, name='StudentRegister'),
    path('teacherlogin/', views.TeacherLoginView, name='LoginTeacher'),
    path('studentlogin/', views.StudentLoginView, name='LoginStudent'),
    path('teacher_dashboard/<int:TeacherID>/', views.teacher_dashboard, name='teacher_dashboard'),  
    path('student_dashboard/<int:StuID>/', views.student_dashboard, name='student_dashboard'),
    path('create_quiz/', views.create_quiz, name='create_quiz'),  
    path('edit_quiz/<int:quiz_id>/', views.edit_quiz, name='edit_quiz'),
    path('delete_quiz/<int:quiz_id>/<int:teacher_id>/', views.delete_quiz, name='delete_quiz'),
    path('take_quiz/<int:stu_id>/<str:quiz_name>/', views.take_quiz, name='take_quiz'),
    path('show_results/<int:stu_id>/', views.show_results, name='show_results'),
    path('view_quiz/<int:quiz_id>/', views.view_quiz, name='view_quiz'),
]


quizproject/urls.py
from django.contrib import admin
from django.urls import path,include
app_name = "quiz"

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('quiz.urls')),
]

quiz/models.py
from django.db import models
from django.utils import timezone
import random

def generate_user_id():
    while True:
        user_id = random.randint(10000000, 99999999)
        if user_id not in TeacherLogin.objects.values_list('TeacherID') and user_id not in StudentLogin.objects.values_list('StuID'):
            return user_id

class TeacherLogin(models.Model):
    TeacherFirstName = models.CharField(max_length=50)
    TeacherLastName = models.CharField(max_length=50)
    TeacherUsername = models.CharField(max_length=30, unique=True)
    TeacherID = models.AutoField( primary_key=True, default=generate_user_id)
    TeacherPassword = models.CharField(max_length=255, default="default_password")
    Subject = models.CharField(max_length=50)
    
    class Meta:
        db_table = 'TeacherLogin'

class StudentLogin(models.Model):
    StuFirstName = models.CharField(max_length=50)
    StuLastName = models.CharField(max_length=50)
    StuUsername = models.CharField(max_length=30, unique=True)
    StuID = models.AutoField( primary_key=True, default=generate_user_id)
    StuPassword = models.CharField(max_length=255, default="default_password")  
    
    class Meta:
        db_table = 'StudentLogin'

class QuizTable(models.Model):
    Subject = models.CharField(max_length=200)
    TID = models.ForeignKey(TeacherLogin, on_delete=models.CASCADE)
    QuizName = models.CharField(max_length=100,unique=True)
    Timestamp = models.DateTimeField(default=timezone.now)
    Deadline = models.DateTimeField()
    MaxAttempts = models.PositiveIntegerField(default=1)
    def is_expired(self):
        return timezone.now() > self.Deadline
    
    class Meta:
       db_table = 'Quizzzz'


       
class Question(models.Model):
    Ques = models.CharField(max_length=1000)
    QuesType = models.CharField(max_length=20, choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('true_false', 'True/False')])
    quiz = models.ForeignKey('QuizTable', on_delete=models.CASCADE)

    class Meta:
        db_table = 'Question'  

class Choice(models.Model):
    Choices1 = models.CharField(max_length=200)
    Choices2 = models.CharField(max_length=200)
    Choices3 = models.CharField(max_length=200)
    Choices4 = models.CharField(max_length=200)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Choice'


class Answer(models.Model):
    Ans = models.CharField(max_length=200)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Answer'

class Results(models.Model):
    SID = models.ForeignKey(StudentLogin, on_delete=models.CASCADE)
    Qname = models.ForeignKey(QuizTable,on_delete=models.CASCADE)
    Score = models.IntegerField()
    DateTime = models.DateTimeField(default=timezone.now)
    MaxAttempts = models.PositiveIntegerField(default=1)
    
    class Meta:
        db_table='Results'






quiz/views.py
from random import sample
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from .models import TeacherLogin, StudentLogin
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import QuizTable, Question, Choice, Answer, Results
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.db.models import ObjectDoesNotExist
from django.utils.timezone import now
from .models import TeacherLogin, QuizTable, Question, Choice, Answer
from django.db.models import Count, F
from django.db.models import Count, F, Value
from django.db.models.functions import Coalesce
def homepage(request):
    return render(request, 'Homepage.html')

def TeacherRegister(request):
    if request.method == "POST":
        TeacherUsername = request.POST.get('TeacherUsername')
        existing_teacher = TeacherLogin.objects.filter(TeacherUsername=TeacherUsername).first()
        if existing_teacher:
            return render(request, 'teachers.html', {'message': 'User already exists'})
        else:
            if request.POST.get('TeacherFirstName') and request.POST.get('TeacherLastName') and TeacherUsername and request.POST.get('TeacherPassword'):
                new_teacher = TeacherLogin()
                new_teacher.TeacherFirstName = request.POST.get('TeacherFirstName')
                new_teacher.TeacherLastName = request.POST.get('TeacherLastName')
                new_teacher.TeacherUsername = TeacherUsername
                new_teacher.TeacherPassword = request.POST.get('TeacherPassword')
                new_teacher.Subject =request.POST.get ('Subject')
                new_teacher.save()
                TeacherID = new_teacher.pk

                return render(request, 'teachers.html', {'TeacherID': TeacherID})

    return render(request, 'teachers.html')

def StudentRegister(request):
    if request.method == "POST":
        StuUsername = request.POST.get('StuUsername')
        existing_stu = StudentLogin.objects.filter(StuUsername=StuUsername).first()
        if existing_stu:
            return render(request, 'student.html', {'message': 'User already exists'})
        else:
            if request.POST.get('StuFirstName') and request.POST.get('StuLastName') and StuUsername and request.POST.get('StuPassword'):
                new_stu = StudentLogin()
                new_stu.StuFirstName = request.POST.get('StuFirstName')
                new_stu.StuLastName = request.POST.get('StuLastName')
                new_stu.StuUsername = StuUsername
                new_stu.StuPassword = request.POST.get('StuPassword')
                new_stu.save()
                StuID = new_stu.pk

                return render(request, 'student.html', {'StuID': StuID})

    return render(request, 'student.html')

def TeacherLoginView(request):
    if request.method == "POST":
        TeacherUsername = request.POST.get('TeacherUsername')
        TeacherPassword = request.POST.get('TeacherPassword')
        
        teacher = TeacherLogin.objects.filter(TeacherUsername=TeacherUsername).first()

        if teacher and teacher.TeacherPassword == TeacherPassword:
            # Authentication successful, redirect to the teacher's dashboard
            return redirect('quiz:teacher_dashboard', TeacherID=teacher.TeacherID)
        else:
            # Authentication failed, return an error message
            return render(request, 'teacher_login.html', {'teacher': teacher, 'message': 'Invalid username or password'})

    return render(request, 'teacher_login.html')

def StudentLoginView(request):
    if request.method == "POST":
        StuUsername = request.POST.get('StuUsername')
        StuPassword = request.POST.get('StuPassword')

        student = StudentLogin.objects.filter(StuUsername=StuUsername).first()

        if student and student.StuPassword == StuPassword:
            # Authentication successful, redirect to the student's dashboard
            return redirect('quiz:student_dashboard', StuID=student.StuID)
        else:
            # Authentication failed, return an error message
            return render(request, 'student_login.html', {'message': 'Invalid username or password'})

    return render(request, 'student_login.html')

def teacher_dashboard(request, TeacherID):
    # Retrieve quizzes for the teacher dashboard based on TeacherID
    quizzes = QuizTable.objects.filter(TID=TeacherID).all()
    return render(request, 'teacher_dashboard.html', {'quizzes': quizzes, 'TeacherID': TeacherID})

def view_quiz(request, quiz_id):
    quiz = get_object_or_404(QuizTable, id=quiz_id)
    questions = Question.objects.filter(quiz=quiz)
    
    # Retrieve choices and answers for each question
    question_details = []
    for question in questions:
        choices = Choice.objects.filter(question=question)
        answer = Answer.objects.get(question=question)
        question_details.append({'question': question, 'choices': choices, 'answer': answer})

    # You can add more data to context if needed
    context = {
        'quiz': quiz,
        'question_details': question_details,
    }

    return render(request, 'view_quiz.html', context)


def student_dashboard(request, StuID):
    student = StudentLogin.objects.get(StuID=StuID)
    quizzes = QuizTable.objects.values('Subject', 'QuizName', 'Deadline', 'MaxAttempts')

    # Retrieve quiz results for the student with attempts information
    results = Results.objects.filter(SID=student).annotate(attempts=Coalesce(Count('Qname'), Value(0)))

    # Update quizzes queryset to include attempts information
    for quiz in quizzes:
        # Get the initial attempts from the quiz results
        initial_attempts = results.filter(Qname__QuizName=quiz['QuizName']).first()

        # If the student is newly registered, use MaxAttempts as initial_attempts
        if initial_attempts is None:
            initial_attempts = quiz['MaxAttempts']
        else:
            # If the student has attempted the quiz, update initial_attempts to reflect actual attempts
            initial_attempts = initial_attempts.MaxAttempts

        # Include attempts information directly in the quizzes queryset
        quiz['initial_attempts'] = initial_attempts
        quiz['max_attempts'] = quiz['MaxAttempts']

    context = {
        'StuID': StuID,
        'student': student,
        'quizzes': quizzes,
        'results': results,
    }

    return render(request, 'student_dashboard.html', context)

def create_quiz(request):
    if request.method == 'POST':
        teacher_id = request.POST['teacher_id']
        quiz_name = request.POST['quiz_name']
        deadline = request.POST['deadline']  
        max_attempts = int(request.POST['max_attempts'])
        
        # Create the quiz with timestamp
        teacher = TeacherLogin.objects.get(TeacherID=teacher_id)
        quiz = QuizTable.objects.create(TID=teacher, QuizName=quiz_name, Subject=teacher.Subject, Timestamp=timezone.now(),Deadline=deadline,MaxAttempts=max_attempts)

        # Process questions, choices, and answers
        questions = request.POST.getlist('questions[]')

        # Ensure there are at least 10 questions
        if len(questions) < 10:
            return HttpResponseBadRequest("A quiz must have at least 10 questions.")

        choices_list = request.POST.getlist('choices[]')
        answers = request.POST.getlist('answers[]')

        for i, question_text in enumerate(questions):
            # Create a question for each iteration
            question = Question.objects.create(quiz=quiz, Ques=question_text)

            # Add choices for the question
            choices = choices_list[i * 4: (i + 1) * 4]
            Choice.objects.create(
                question=question,
                Choices1=choices[0],
                Choices2=choices[1],
                Choices3=choices[2],
                Choices4=choices[3]
            )

            # Add answer for the question
            Answer.objects.create(question=question, Ans=answers[i])

        # Redirect to the teacher dashboard after creating the quiz
        return redirect('quiz:teacher_dashboard', TeacherID=teacher_id)

    teachers = TeacherLogin.objects.all()
    return render(request, 'create_quiz.html', {'teachers': teachers})


def edit_quiz(request, quiz_id):
    quiz = get_object_or_404(QuizTable, pk=quiz_id)

    if request.method == 'POST':
        # Handle the form submission for editing quiz details
        quiz_name = request.POST.get('quiz_name')
        quiz.QuizName = quiz_name

        # Update deadline and max attempts
        quiz.Deadline = request.POST.get('deadline')
        quiz.MaxAttempts = int(request.POST.get('max_attempts'))
        quiz.save()

        # Process questions, choices, and answers
        questions = request.POST.getlist('questions[]')

        # Ensure there are at least 10 questions
        if len(questions) < 10:
            return HttpResponseBadRequest("A quiz must have at least 10 questions.")

        choices_list = request.POST.getlist('choices[]')
        answers = request.POST.getlist('answers[]')

        # Clear existing questions not present in the submitted list
        existing_questions = quiz.question_set.all()
        for question in existing_questions:
            if question.Ques not in questions:
                question.delete()

        # Update or create questions, choices, and answers
        for i, question_text in enumerate(questions):
            question, created = Question.objects.get_or_create(quiz=quiz, Ques=question_text)

            # Handle choices if they exist
            choices = choices_list[i * 4: (i + 1) * 4]

quiz/templates/Homepage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiz Home Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <style>
        body {
            font-family: 'VALORANT';
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: row;
            justify-content: space-around;
            align-items: center;
            height: 100vh;
        }
        
        #section1 {
            background-color: #2EB7B5;
            width: 50%;
            height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            color: #222;
            font-size: 70px;
            
        }
        
        #section1 h1 {
            font-size: 120px;
            margin-bottom: 20px;
        }
        
        #section2 {
            background-color: #222;
            width: 50%;
            height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }
        
        .button-container {
            display: flex;
            flex-direction: row; /* Change to row */
            gap: 29px;
            align-items: center; /* Add this line */
        }
        
        a {
            text-decoration: none;
        }
        
        button.student,
        button.teacher {
            padding: 20px 30px;
            font-size: 18px;
            border: none;
            border-radius: 30px;
            cursor: pointer;
            width: 150px;
            transition: background-color 0.3s ease;
        }
        
        button.student {
            background-color: #F42249;
            color: #fff;
        }
        
        button.teacher {
            background-color: #fff;
            color: #222;
        }
        
        button:hover {
            background-color: ;
        }
        
        img {
            max-width: 100%;
            border-radius: 15px;
            margin-bottom: 15px;
        }
    </style>
</head>

<body>

    <div id="section1">
        <h1>Q U I Z </h1>
    </div>

    <div id="section2" class="button-container">
        <img src="https://www.free-css.com/assets/files/free-css-templates/preview/page296/spering/assets/images/slider-img.png" alt="Quiz Image">
        <a href="{% url 'quiz:StudentRegister' %}"><button class="student">STUDENT</button></a>
        <a href="{% url 'quiz:TeacherRegister' %}"><button class="teacher">TEACHER</button></a>
    </div>

</body>

</html>

quiz/templates/delete_quiz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Quiz</title>
    <!-- Add any additional stylesheets or scripts as needed -->
</head>
<body>

<!-- Display confirmation message -->
<h2>Delete Quiz</h2>
<p>Are you sure you want to delete the quiz "{{ quiz.QuizName }}"?</p>

<!-- Confirm or cancel the deletion -->
<form method="post" action="{% url 'quiz:delete_quiz' quiz_id=quiz.id teacher_id=quiz.TID.TeacherID %}">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">
    <a href="{% url 'quiz:delete_quiz' quiz_id=quiz.id teacher_id=quiz.TID.TeacherID %}">Cancel</a>
</form>

</body>
</html>

quiz/templates/show_results.html
<!-- show_results.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Quiz Results</title>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
    }

    h1 {
      text-align: center;
      color: #333;
    }

    table {
      width: 80%;
      margin: 20px auto;
      border-collapse: collapse;
      background-color: #fff;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    th, td {
      padding: 15px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }

    th {
      background-color: #f2f2f2;
    }

    tbody tr:hover {
      background-color: #f5f5f5;
    }

    p {
      text-align: center;
      color: #777;
    }
  </style>
</head>
<body>
  <h1>Quiz Results</h1>

  {% if results %}
    <table>
      <thead>
        <tr>
          <th>Quiz Name</th>
          <th>Score</th>
          <th>Date and Time</th>
        </tr>
      </thead>
      <tbody>
        {% for result in results %}
          <tr>
            <td>{{ result.Qname.QuizName }}</td>
            <td>{{ result.Score }}</td>
            <td>{{ result.DateTime }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No quiz results available.</p>
  {% endif %}
</body>
</html>

quiz/templates/student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Page</title>
    <link rel="stylesheet" href="path/to/config.css">
    <style>
        body {
            background-color: #2c3338;
            color: #fff;
            font-family: 'Open Sans', sans-serif;
            font-size: 16px;
            line-height: 1.6;
            margin: 0;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .form-container {
            background-color: #363b41;
            border-radius: 45px;
            padding: 30px;
            max-width: 400px;
            width: 90%;
            text-align: center;
        }

        .form__field {
            display: flex;
            flex-direction: column;
            margin-bottom: 20px;
        }

        .form__label {
            background-color: #363b41;
            border-radius: 46px;
            padding: 10px;
            text-align: left;
            margin-bottom: 8px;
        }

        .form__input {
            width: 85%;
            padding: 12px;
            border: 1px solid #5D6D7E;
            border-radius: 93px;
            background-color: #3b4148;
            color: #fff;
            transition: background-color 0.3s;
        }

        .form__input:focus,
        .form__input:hover {
            background-color: #434a52;
        }

        .form__submit {
            background-color: #F42249;
            color: #eee;
            font-weight: 700;
            text-transform: uppercase;
            cursor: pointer;
            padding: 12px;
            border: none;
            border-radius: 4px;
            transition: background-color 0.3s;
        }

        .form__submit:focus,
        .form__submit:hover {
            background-color: #ea4c88;
        }

        .login__button {
            background-color: #F42249;
            color: white;
            padding: 12px 20px;
            border: bottom;
            border-radius: 4px;
            text-decoration: none;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s;
        }

        .login__button:hover {
            background-color: #ea4c88;
        }

        .response {
            text-align: center;
            margin-top: 20px;
            color: #aaffaa;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <h1>STUDENT REGISTRATION</h1>

        <form class="form" method="post">
            {% csrf_token %}
            <div class="form__field">
                <label class="form__label" for="id_StuFirstName">First Name:</label>
                <input class="form__input" type="text" id="id_StuFirstName" name="StuFirstName" required>
            </div>

            <div class="form__field">
                <label class="form__label" for="id_StuLastName">Last Name:</label>
                <input class="form__input" type="text" id="id_StuLastName" name="StuLastName" required>
            </div>

            <div class="form__field">
                <label class="form__label" for="id_StuUsername">Username:</label>
                <input class="form__input" type="text" id="id_StuUsername" name="StuUsername" required>
            </div>

            <div class="form__field">
                <label class="form__label" for="id_StuPassword">Password:</label>
                <input class="form__input" type="password" id="id_StuPassword" name="StuPassword" required>
            </div>

            <input class="form__submit" type="submit" value="Register">
            <div>
                <a href="{% url 'quiz:LoginStudent' %}" class="login__button">Login</a>
            </div>
        </form>
    </div>

    <!-- Login Button -->
   
    <img src="https://www.dummydevelopers.com/girl-bro.svg" alt="Quiz Image">

    {% if StuID %}
    <p class="response">Thank you for registering! Your Student ID is: {{ StuID }}</p>
    {% endif %}
    {% if message %}
    <p class="response">{{ message }}</p>
    {% endif %}
</body>
</html>

quiz/templates/teacher_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teacher Dashboard</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 20px;
            background-color: #f4f4f4;
        }

        h2 {
            color: #333;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
        }

        td.action-buttons a {
            margin-right: 10px;
            text-decoration: none;
            color: #007bff;
        }

        td.action-buttons a:hover {
            text-decoration: underline;
        }

        .create-quiz-button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #0002ff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }
    </style>
</head>
<body>

    <h2>Teacher Dashboard</h2>
    <!-- Display teacher dashboard -->
    <table>
        <thead>
            <tr>
                <th>Teacher ID</th>
                <th>Subject</th>
                <th>Quiz Name</th>
                <th>Attempts</th>
                <th>Deadline</th>
                <th>Timestamp</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for quiz in quizzes %}
            <tr>
                <td>{{ quiz.TID.TeacherID }}</td>
                <td>{{ quiz.TID.Subject }}</td>
                <td>{{ quiz.QuizName }}</td>
                <td>{{ quiz.MaxAttempts }}</td>
                <td>{{ quiz.Deadline }}</td>
                <td>{{ quiz.Timestamp }}</td>
                <td class="action-buttons">
                    <a href="{% url 'quiz:view_quiz' quiz_id=quiz.id %}">View</a>
                    <a href="{% url 'quiz:edit_quiz' quiz_id=quiz.id %}">Edit</a>
                    <a href="{% url 'quiz:delete_quiz' quiz_id=quiz.id teacher_id=quiz.TID.TeacherID %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <!-- Create quiz button -->
    <a href="{% url 'quiz:create_quiz' %}" class="create-quiz-button">Create Quiz</a>

</body>
</html>

quiz/templates/teachers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teachers Page</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background: url('https://i.pinimg.com/736x/18/51/a7/1851a7a2a83f1d3f05db1b0d22d19a49.jpg') no-repeat center center fixed;
            background-size: cover;
            color: #fff;
            display: flex;
            flex-direction: column;
            align-items: center;
            height: 70vh;
        }

        h1 {
            color: #fff;
            text-align: center;
            font-size: 66px;
            margin-bottom: 20px;
        }

        form {
            background-color: #BCC6CC;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            margin: auto;
            box-sizing: border-box;
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 8px;
            color: #000000;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 12px;
            margin-bottom: 20px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 6px;
            transition: border-color 0.3s ease;
        }

        input[type="text"]:focus,
        input[type="password"]:focus {
            border-color: #4caf50;
        }

        input[type="submit"] {
            background-color: #0002FF;
            color: #fff;
            padding: 12px 20px;
            border: none;
            border-radius: 6px;
            cursor: pointer;
            font-size: 16px;
            transition: background-color 0.3s ease;
        }

        input[type="submit"]:hover {
            background-color: #0002FF;
        }

        section {
            margin-top: 20px;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 100%;
            box-sizing: border-box;
            margin-bottom: 20px;
        }

        h2 {
            color: #333;
        }

        p {
            color: #fff;
            text-align: center;
        }

        div {
            text-align: center;
        }

        a {
            text-decoration: none;
        }

        button {
            background-color: #0002FF;
            color: #fff;
            padding: 20px 30px;
            font-size: 18px;
            border: none;
            border-radius: 30px;
            cursor: pointer;
            width: 150px;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #0002FF;
        }
    </style>
</head>
<body>
    <h1>Teacher Registration  /  Login</h1>

    {% if form.errors %}
        <div style="color: red; text-align: center;">
            <p>Error in the form:</p>
            <ul>
                {% for error in form.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}

        <!-- Teacher Registration Form Fields -->
        <label for="id_TeacherFirstName">First Name:</label>
        <input type="text" id="id_TeacherFirstName" name="TeacherFirstName" required>

        <label for="id_TeacherLastName">Last Name:</label>
        <input type="text" id="id_TeacherLastName" name="TeacherLastName" required>

        <label for="id_TeacherUsername">Username:</label>
        <input type="text" id="id_TeacherUsername" name="TeacherUsername" required>

        <label for="id_TeacherPassword">Password:</label>
        <input type="password" id="id_TeacherPassword" name="TeacherPassword" required>

        <label for="id_Subject">Subject:</label>
        <input type="text" id="id_Subject" name="Subject" required>

        <input type="submit" value="Register">
    </form>

    <!-- Login Button -->
    <div style="text-align: center; margin-top: 20px;">
        <a href="{% url 'quiz:LoginTeacher' %}">
            <button>Login</button>
        </a>
    </div>

    {% if TeacherID %}
        <p style="text-align: center;">Thank you for registering! Your Teacher ID is: {{ TeacherID }}</p>
    {% endif %}
    {% if message %}
        <p style="text-align: center;">{{ message }}</p>
    {% endif %}
</body>
</html>